/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HLRCallback {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("msisdn")
  private Long msisdn = null;
  public enum StatusEnum {
     valid,  invalid,  unknown, 
  };
  @SerializedName("status")
  private StatusEnum status = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("operator")
  private String operator = null;
  @SerializedName("mccmnc")
  private Integer mccmnc = null;
  public enum DurationEnum {
     perm,  temp, 
  };
  @SerializedName("duration")
  private DurationEnum duration = null;
  @SerializedName("message")
  private String message = null;
  @SerializedName("extended")
  private String extended = null;
  @SerializedName("cost")
  private Float cost = null;

  /**
   * Unique ID for response
   **/
  @ApiModelProperty(value = "Unique ID for response")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * The MSISDN of the number queried
   **/
  @ApiModelProperty(value = "The MSISDN of the number queried")
  public Long getMsisdn() {
    return msisdn;
  }
  public void setMsisdn(Long msisdn) {
    this.msisdn = msisdn;
  }

  /**
   * Short status code of the response
   **/
  @ApiModelProperty(value = "Short status code of the response")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  /**
   * ISO 3166-2 country code
   **/
  @ApiModelProperty(value = "ISO 3166-2 country code")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   * The operator attached to the MSISDN
   **/
  @ApiModelProperty(value = "The operator attached to the MSISDN")
  public String getOperator() {
    return operator;
  }
  public void setOperator(String operator) {
    this.operator = operator;
  }

  /**
   * MCC and MNC of MSDISDN
   **/
  @ApiModelProperty(value = "MCC and MNC of MSDISDN")
  public Integer getMccmnc() {
    return mccmnc;
  }
  public void setMccmnc(Integer mccmnc) {
    this.mccmnc = mccmnc;
  }

  /**
   * If the response code is temporary or permenant
   **/
  @ApiModelProperty(value = "If the response code is temporary or permenant")
  public DurationEnum getDuration() {
    return duration;
  }
  public void setDuration(DurationEnum duration) {
    this.duration = duration;
  }

  /**
   * Full status code of the response
   **/
  @ApiModelProperty(value = "Full status code of the response")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   * Extended explanation of the status code
   **/
  @ApiModelProperty(value = "Extended explanation of the status code")
  public String getExtended() {
    return extended;
  }
  public void setExtended(String extended) {
    this.extended = extended;
  }

  /**
   * Cost of the response
   **/
  @ApiModelProperty(value = "Cost of the response")
  public Float getCost() {
    return cost;
  }
  public void setCost(Float cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLRCallback hLRCallback = (HLRCallback) o;
    return (this.id == null ? hLRCallback.id == null : this.id.equals(hLRCallback.id)) &&
        (this.msisdn == null ? hLRCallback.msisdn == null : this.msisdn.equals(hLRCallback.msisdn)) &&
        (this.status == null ? hLRCallback.status == null : this.status.equals(hLRCallback.status)) &&
        (this.country == null ? hLRCallback.country == null : this.country.equals(hLRCallback.country)) &&
        (this.operator == null ? hLRCallback.operator == null : this.operator.equals(hLRCallback.operator)) &&
        (this.mccmnc == null ? hLRCallback.mccmnc == null : this.mccmnc.equals(hLRCallback.mccmnc)) &&
        (this.duration == null ? hLRCallback.duration == null : this.duration.equals(hLRCallback.duration)) &&
        (this.message == null ? hLRCallback.message == null : this.message.equals(hLRCallback.message)) &&
        (this.extended == null ? hLRCallback.extended == null : this.extended.equals(hLRCallback.extended)) &&
        (this.cost == null ? hLRCallback.cost == null : this.cost.equals(hLRCallback.cost));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.msisdn == null ? 0: this.msisdn.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.operator == null ? 0: this.operator.hashCode());
    result = 31 * result + (this.mccmnc == null ? 0: this.mccmnc.hashCode());
    result = 31 * result + (this.duration == null ? 0: this.duration.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.extended == null ? 0: this.extended.hashCode());
    result = 31 * result + (this.cost == null ? 0: this.cost.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLRCallback {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  msisdn: ").append(msisdn).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  operator: ").append(operator).append("\n");
    sb.append("  mccmnc: ").append(mccmnc).append("\n");
    sb.append("  duration: ").append(duration).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  extended: ").append(extended).append("\n");
    sb.append("  cost: ").append(cost).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
