/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class HLRResult {
  
  @SerializedName("status")
  private String status = null;
  @SerializedName("success")
  private List<Long> success = null;
  @SerializedName("failure")
  private List<Long> failure = null;
  @SerializedName("cost")
  private Float cost = null;
  @SerializedName("callback")
  private String callback = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Long> getSuccess() {
    return success;
  }
  public void setSuccess(List<Long> success) {
    this.success = success;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Long> getFailure() {
    return failure;
  }
  public void setFailure(List<Long> failure) {
    this.failure = failure;
  }

  /**
   * Cost of the response
   **/
  @ApiModelProperty(value = "Cost of the response")
  public Float getCost() {
    return cost;
  }
  public void setCost(Float cost) {
    this.cost = cost;
  }

  /**
   * Callback URL provided
   **/
  @ApiModelProperty(value = "Callback URL provided")
  public String getCallback() {
    return callback;
  }
  public void setCallback(String callback) {
    this.callback = callback;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLRResult hLRResult = (HLRResult) o;
    return (this.status == null ? hLRResult.status == null : this.status.equals(hLRResult.status)) &&
        (this.success == null ? hLRResult.success == null : this.success.equals(hLRResult.success)) &&
        (this.failure == null ? hLRResult.failure == null : this.failure.equals(hLRResult.failure)) &&
        (this.cost == null ? hLRResult.cost == null : this.cost.equals(hLRResult.cost)) &&
        (this.callback == null ? hLRResult.callback == null : this.callback.equals(hLRResult.callback));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.failure == null ? 0: this.failure.hashCode());
    result = 31 * result + (this.cost == null ? 0: this.cost.hashCode());
    result = 31 * result + (this.callback == null ? 0: this.callback.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLRResult {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  success: ").append(success).append("\n");
    sb.append("  failure: ").append(failure).append("\n");
    sb.append("  cost: ").append(cost).append("\n");
    sb.append("  callback: ").append(callback).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
