/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SMSResult {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("success")
  private Integer success = null;
  @SerializedName("cost")
  private Float cost = null;
  @SerializedName("count")
  private Integer count = null;
  @SerializedName("failure")
  private List<String> failure = null;

  /**
   * Unique ID for response
   **/
  @ApiModelProperty(value = "Unique ID for response")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Count of queued SMS
   **/
  @ApiModelProperty(value = "Count of queued SMS")
  public Integer getSuccess() {
    return success;
  }
  public void setSuccess(Integer success) {
    this.success = success;
  }

  /**
   * Cost of the SMS
   **/
  @ApiModelProperty(value = "Cost of the SMS")
  public Float getCost() {
    return cost;
  }
  public void setCost(Float cost) {
    this.cost = cost;
  }

  /**
   * Total count of SMS queued
   **/
  @ApiModelProperty(value = "Total count of SMS queued")
  public Integer getCount() {
    return count;
  }
  public void setCount(Integer count) {
    this.count = count;
  }

  /**
   * List of failed numbers
   **/
  @ApiModelProperty(value = "List of failed numbers")
  public List<String> getFailure() {
    return failure;
  }
  public void setFailure(List<String> failure) {
    this.failure = failure;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SMSResult sMSResult = (SMSResult) o;
    return (this.id == null ? sMSResult.id == null : this.id.equals(sMSResult.id)) &&
        (this.success == null ? sMSResult.success == null : this.success.equals(sMSResult.success)) &&
        (this.cost == null ? sMSResult.cost == null : this.cost.equals(sMSResult.cost)) &&
        (this.count == null ? sMSResult.count == null : this.count.equals(sMSResult.count)) &&
        (this.failure == null ? sMSResult.failure == null : this.failure.equals(sMSResult.failure));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.success == null ? 0: this.success.hashCode());
    result = 31 * result + (this.cost == null ? 0: this.cost.hashCode());
    result = 31 * result + (this.count == null ? 0: this.count.hashCode());
    result = 31 * result + (this.failure == null ? 0: this.failure.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SMSResult {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  success: ").append(success).append("\n");
    sb.append("  cost: ").append(cost).append("\n");
    sb.append("  count: ").append(count).append("\n");
    sb.append("  failure: ").append(failure).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
