/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiInvoker;
import io.swagger.client.ApiException;
import io.swagger.client.Pair;

import io.swagger.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import io.swagger.client.model.HLRError;
import io.swagger.client.model.OutOfCredit;
import io.swagger.client.model.SMSResult;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class SMSApi {
  String basePath = "https://api.smsfusion.com.au/";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * Send an SMS
  * Send one or more SMS
   * @param key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;
   * @param num Comma separated list of phone numbers or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;&#39;s
   * @param msg Message content to send
   * @param from MSISDN or vanity alphanumeric source number
   * @param deliverby UTC encoded time to send the SMS
   * @param dlrcb HTTP or HTTPS callback URL for delivery reports. Timeout for callbacks is set to 30 seconds
   * @param replycb HTTP or HTTPS callback URL for replies. Timeout for callbacks is set to 30 seconds
   * @param replyemail Email address to send replies to
   * @param validity Time in minutes to keep the SMS valid for
   * @param cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally
   * @return SMSResult
  */
  public SMSResult sendSMS (String key, List<String> num, String msg, String from, String deliverby, String dlrcb, String replycb, String replyemail, Integer validity, String cc) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'key' is set
    if (key == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'key' when calling sendSMS",
        new ApiException(400, "Missing the required parameter 'key' when calling sendSMS"));
    }
    // verify the required parameter 'num' is set
    if (num == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'num' when calling sendSMS",
        new ApiException(400, "Missing the required parameter 'num' when calling sendSMS"));
    }
    // verify the required parameter 'msg' is set
    if (msg == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'msg' when calling sendSMS",
        new ApiException(400, "Missing the required parameter 'msg' when calling sendSMS"));
    }

    // create path and map variables
    String path = "/sms/".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    queryParams.addAll(ApiInvoker.parameterToPairs("", "key", key));
    queryParams.addAll(ApiInvoker.parameterToPairs("csv", "num", num));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "msg", msg));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "from", from));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "deliverby", deliverby));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "dlrcb", dlrcb));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "replycb", replycb));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "replyemail", replyemail));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "validity", validity));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "cc", cc));
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "api_key" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (SMSResult) ApiInvoker.deserialize(localVarResponse, "", SMSResult.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
       if (ex.getCause() instanceof VolleyError) {
         VolleyError volleyError = (VolleyError)ex.getCause();
         if (volleyError.networkResponse != null) {
           throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
         }
       }
       throw ex;
    } catch (TimeoutException ex) {
       throw ex;
    }
  }

      /**
   * Send an SMS
   * Send one or more SMS
   * @param key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;   * @param num Comma separated list of phone numbers or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;&#39;s   * @param msg Message content to send   * @param from MSISDN or vanity alphanumeric source number   * @param deliverby UTC encoded time to send the SMS   * @param dlrcb HTTP or HTTPS callback URL for delivery reports. Timeout for callbacks is set to 30 seconds   * @param replycb HTTP or HTTPS callback URL for replies. Timeout for callbacks is set to 30 seconds   * @param replyemail Email address to send replies to   * @param validity Time in minutes to keep the SMS valid for   * @param cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally
  */
  public void sendSMS (String key, List<String> num, String msg, String from, String deliverby, String dlrcb, String replycb, String replyemail, Integer validity, String cc, final Response.Listener<SMSResult> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

  
    // verify the required parameter 'key' is set
    if (key == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'key' when calling sendSMS",
         new ApiException(400, "Missing the required parameter 'key' when calling sendSMS"));
    }
    
    // verify the required parameter 'num' is set
    if (num == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'num' when calling sendSMS",
         new ApiException(400, "Missing the required parameter 'num' when calling sendSMS"));
    }
    
    // verify the required parameter 'msg' is set
    if (msg == null) {
       VolleyError error = new VolleyError("Missing the required parameter 'msg' when calling sendSMS",
         new ApiException(400, "Missing the required parameter 'msg' when calling sendSMS"));
    }
    

    // create path and map variables
    String path = "/sms/".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();

    queryParams.addAll(ApiInvoker.parameterToPairs("", "key", key));
    queryParams.addAll(ApiInvoker.parameterToPairs("csv", "num", num));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "msg", msg));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "from", from));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "deliverby", deliverby));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "dlrcb", dlrcb));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "replycb", replycb));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "replyemail", replyemail));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "validity", validity));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "cc", cc));


    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

      String[] authNames = new String[] { "api_key" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((SMSResult) ApiInvoker.deserialize(localVarResponse,  "", SMSResult.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
